### ISSUE TITLE
Refactor to use an error handler for non success status codes

### ISSUE THREAD

**Issue by jpeterson88** [ayovev/retirement-tracking-app#4]
When a status code that is anything but a 200 range, we'll want to handle that properly without completely crashing the app. We can create an error handler class that performs some type of logging so that we fail gracefully and respond to the client with a nice message. 

Example: if we get a 401 from the API because our API token has expired, we want to log this and potentially send a notification to the dev team. From there, we could send a message down to the client with a nice message so they don't start receiving a bunch of 404s or 500s because the server is down

https://github.com/ayovev/retirement-tracking-app/blob/bec2b95d8102c9e53f7ee27ab5c4a17d19a964e5/server/src/getData.js#L35

**Comment by ayovev** [comment]
I completely agree! Do you think this is something that we can implement by simply using a try-catch block and gracefully handling the error?

**Comment by jpeterson88** [comment]
No, we should create a new script / class that handles this type of thing. We would remove the assert and do something like: httpResponseHandler.handle(response) and underneath the covers, have it check the status code and from there we'd handle each status code appropriately. It would be used on the responses for all of our status codes.

**Comment by ayovev** [comment]
The only problem with that is that the API sends back a 200 code every time whether it succeeded or not...If it encounters an error it'll send back a 200 with an error message in the body. I'm working on dealing with that right now.

**Comment by jpeterson88** [comment]
Is that a public API?

**Comment by ayovev** [comment]
Yes -- the only authentication is with an API key. But I've built a small function that should perform that check.

**Comment by ayovev** [comment]
@jpeterson88 Are we good to close this issue?

**Comment by jpeterson88** [comment]
@ayovev yeah, it's more of a task we'll want to address at a later time. Maybe just add a todo and call it a day.
